---

- name: Copy files to remote server
  when: inventory_hostname in groups['ora-x3']
  become: true
  block:
    - name: Copy sink connector scriplst to remote server
      ansible.builtin.copy:
        src: ../../../../../challenge-3/package/challenge3.tar
        dest: /challenge3.tar
        owner: oracle
        mode: '0644'

- name: Unarchive the zip file on remote VM
  when: inventory_hostname in groups['ora-x3']
  ansible.builtin.unarchive:
    src: /challenge3.tar
    dest: /
    remote_src: yes

